ENH: Render an intermediate PDF and use qpdf to overlay that with the original PDF
This avoids that the original PDF is rendered as an image; i.e. text remains selectable and the overall file size likely is smaller, too. (For a one-page letter with my letterhead, the difference was 700 kB vs. 1.3 MB.)
Offer the original algorithm via --direct flag.

diff --git a/bin/add-signature b/bin/add-signature
--- a/bin/add-signature
+++ b/bin/add-signature
@@ -3,11 +3,16 @@
 : ${ADDSIGNATURE_EXT:=signed}
 : ${ADDSIGNATURE_FILESPEC:="${XDG_CONFIG_HOME:-${HOME}/.config}/signature.png"}
 
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+readonly projectDir="${scriptDir}/.."
+readonly etcDir="${projectDir}/etc/$(basename -- "${BASH_SOURCE[0]}")"
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '([-%|--at VERTICAL-PERCENTAGE] [-c|--center|-r|--right] | [--geometry WxH(+-)X(+-)Y]) [-o|--to TARGETDIR] [--] PDF-FILE [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--direct] ([-%|--at VERTICAL-PERCENTAGE] [-c|--center|-r|--right] | [--geometry [WxH](+-)X(+-)Y]) [-o|--to TARGETDIR] [--] PDF-FILE [...] [-?|-h|--help]'
 }
 printUsage()
 {
@@ -28,18 +33,25 @@ HELPDESCRIPTION
     printShortUsage "$1"
     echo
     cat <<HELPTEXT
+    --direct		Directly add the signature to the PDF file, instead of
+			adding and overlaying a separate page. This converts the
+			entire PDF from text to image format, resulting in a
+			larger file size. Only do this if the original PDF isn't
+			text-based or if you explicitly want to turn it into an
+			image.
     --at|-% VERTICAL-PERCENTAGE
 			The vertical percentage of the page where the signature
 			should be placed. Default is ${pagePercentage}% from the top.
     --center|-c		Place the signature in the center of the page. Default
 			is ${alignment}.
     --right|-r		Place the signature on the right side of the page.
-    --geometry WxH(+-)X(+-)Y
-			Place the signature at X/Y with a size of WxH.
+    --geometry [WxH](+-)X(+-)Y
+			Place the signature at X/Y [with a size of WxH].
     --to|-o TARGETDIR	Place the signed PDFs in the specified directory.
 HELPTEXT
 }
 
+isDirect=
 pagePercentage=80
 alignment=West
 alignmentOffset=250
@@ -49,6 +61,7 @@ while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
+	--direct)	shift; isDirect=t;;
 	--at|-%)	shift; pagePercentage=${1:?}; shift;;
 	--right|-r)	shift; alignment=East; alignmentOffset=100;;
 	--center|-c)	shift; alignment=''; alignmentOffset=0;;
@@ -81,14 +94,27 @@ for pdf
 do
     dirspec="${targetDirspec:-$(dirname -- "$pdf")}"
     targetPdf="${dirspec}/$(fileExtension --basename --splice ".${ADDSIGNATURE_EXT}" "$pdf")"
+    if [ "$isDirect" ]; then
+	sourcePdf="$pdf"
+	conversionTarget="$targetPdf"
+    else
+	sourcePdf="${etcDir}/blank.pdf"
+	conversionTarget="$(mktemp --tmpdir "$(basename -- "$0")-XXXXXX.pdf" 2>/dev/null || echo "${TMPDIR:-/tmp}/$(basename -- "$0").$$${RANDOM}.pdf")"
+    fi
 
     convert \
 	-density 300 \
-	"$pdf" \
+	"$sourcePdf" \
 	"$ADDSIGNATURE_FILESPEC" \
 	"${positionArgs[@]}" \
 	-compose multiply -composite \
-	"$targetPdf" || { status=$?; continue; }
+	"$conversionTarget" || { status=$?; continue; }
+
+    if [ ! "$isDirect" ]; then
+	# Taken from pdfletterhead.
+	qpdf --overlay "$conversionTarget" --to=1 -- "$pdf" "$targetPdf" || { status=$?; continue; }
+	[ "${DEBUG:-}" ] || rm --force -- "$conversionTarget"
+    fi
 
     printf '%s\n' "$targetPdf"
 done
