fakescan: Robustness: Handle [--]

diff --git a/fakescan b/fakescan
--- a/fakescan
+++ b/fakescan
@@ -13,16 +13,22 @@ HELPTEXT
     printf 'Usage: %q %s\n' "$(basename "$1")" '[-o|--to TARGETDIR] [--] PDF-FILE [...] [-?|-h|--help]'
 }
 targetDirspec=
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --to|-o)		shift
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--to|-o)	shift
 			if [ ! -d "$1" ]; then
 			    printf >&2 "ERROR: Target directory '%s' does not exist\\n" "$1"
 			    exit 2
 			fi
 			targetDirspec="${1:?}"; shift
 			;;
-esac
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 if [ $# -eq 0 ]; then
     printUsage "$0" >&2
     exit 2
